"""Notion property IDs for the Transactions data source.

AUTO-GENERATED by scripts/gen_property_ids.py — do not hand-edit the IDs.

Notion property IDs are stable across renames, so the sync keys writes/reads by
ID (not display name). Renaming a property in the Notion UI therefore never
breaks anything. Regenerate only if the data source is recreated.

``NAMES`` keeps the display name each ID mapped to at generation time, for
migrations.py (which must create properties BY name) and for readability.
"""

from __future__ import annotations


class P:
    """Stable Notion property IDs (reference these, never the display names)."""

    NAME = "title"
    AMOUNT = "%40%3DeX"
    DATE = "apGe"
    STATUS = "bNqL"
    SOURCE_ID = "c%5BvI"
    SOURCE_ACCOUNT_ID = "TatA"
    PAYEE = "G%5DBY"
    MEMO = "qpd%5B"
    BANK_CATEGORY = "Loz%7B"
    CATEGORY = "Hj%7CJ"
    BANK = "INs%3B"
    CREDIT_CARD_ACCOUNT = "%3E%7D%7Bt"
    CARD_NETWORK = "Xx%7Cq"
    ACCOUNT_TYPE = "dJ%7C%7C"
    ACCOUNT_NAME = "KND%3D"
    CALCULATED_REWARDS = "GVVr"
    TRUE_REWARDS = "_U~%40"
    REWARDS_TYPE = "Pz%5Eo"
    BILT_POINTS = "t%5DBn"
    BILT_PARTNER = "%3Aycu"
    EXCLUDED = "%5EepD"
    QUANTITY = "JXmA"
    TICKER = "%3BmS%3E"
    PRICE_PER_SHARE = "efsI"
    REVIEW_STATUS = "%3E%7BtH"
    RELEASE_DATE = "yUd%7D"
    NET_AMOUNT = "MGRT"
    RELATED_TRANSACTIONS = "J%5C%7B%3A"
    RELATED_TRANSACTIONS_AMOUNT = "m%3Evy"


# Display name each ID mapped to at generation time (for migrations.py).
NAMES: dict[str, str] = {
    P.NAME: 'Name',
    P.AMOUNT: 'Txn Amount',
    P.DATE: 'Transaction Date',
    P.STATUS: 'Transaction Status',
    P.SOURCE_ID: 'Transaction Source ID',
    P.SOURCE_ACCOUNT_ID: 'Source Account ID',
    P.PAYEE: 'Payee',
    P.MEMO: 'Memo',
    P.BANK_CATEGORY: 'Bank Category',
    P.CATEGORY: 'Category',
    P.BANK: 'Bank',
    P.CREDIT_CARD_ACCOUNT: 'Credit Card / Account',
    P.CARD_NETWORK: 'Card Network',
    P.ACCOUNT_TYPE: 'Account Type',
    P.ACCOUNT_NAME: 'Account Name',
    P.CALCULATED_REWARDS: 'Calculated Rewards',
    P.TRUE_REWARDS: 'True Rewards',
    P.REWARDS_TYPE: 'Rewards Type',
    P.BILT_POINTS: 'Bilt Points',
    P.BILT_PARTNER: 'Bilt Partner',
    P.EXCLUDED: 'Excluded',
    P.QUANTITY: 'Qty',
    P.TICKER: 'Ticker',
    P.PRICE_PER_SHARE: 'PPS',
    P.REVIEW_STATUS: 'Review Status',
    P.RELEASE_DATE: 'Release Date',
    P.NET_AMOUNT: 'Net Amount',
    P.RELATED_TRANSACTIONS: 'Related Transactions',
    P.RELATED_TRANSACTIONS_AMOUNT: 'Related Transactions Amount',
}
