"""Generate notion/properties.py — pin each field's Notion property ID.

Notion property IDs are STABLE across renames, so the sync references IDs (not
display names) and a rename in the Notion UI never breaks a write/read. Run this
once, and again only if the data source is recreated (recreation mints new IDs).

    uv run scripts/gen_property_ids.py
"""

from __future__ import annotations

import asyncio

import httpx

from notion_finance_sync.config.settings import (
    NOTION_API_VERSION,
    NOTION_TRANSACTIONS_DATA_SOURCE_ID,
    get_notion_api_key,
)

# Semantic constant -> current Notion display name. The NAME can change freely in
# the UI; we resolve it to a stable ID here and pin the ID. Keep this list in sync
# with the fields the code actually reads/writes.
SEMANTIC_TO_NAME: dict[str, str] = {
    "NAME": "Name",
    "AMOUNT": "Txn Amount",
    "DATE": "Transaction Date",
    "STATUS": "Transaction Status",
    "SOURCE_ID": "Transaction Source ID",
    "SOURCE_ACCOUNT_ID": "Source Account ID",
    "PAYEE": "Payee",
    "MEMO": "Memo",
    "BANK_CATEGORY": "Bank Category",
    "CATEGORY": "Category",
    "BANK": "Bank",
    "CREDIT_CARD_ACCOUNT": "Credit Card / Account",
    "CARD_NETWORK": "Card Network",
    "ACCOUNT_TYPE": "Account Type",
    "ACCOUNT_NAME": "Account Name",
    "CALCULATED_REWARDS": "Calculated Rewards",
    "TRUE_REWARDS": "True Rewards",
    "REWARDS_TYPE": "Rewards Type",
    "BILT_POINTS": "Bilt Points",
    "BILT_PARTNER": "Bilt Partner",
    "EXCLUDED": "Excluded",
    "QUANTITY": "Qty",
    "TICKER": "Ticker",
    "PRICE_PER_SHARE": "PPS",
    "REVIEW_STATUS": "Review Status",
    "RELEASE_DATE": "Release Date",
    # Computed / manual fields the encoder must NEVER write (guarded by tests).
    "NET_AMOUNT": "Net Amount",
    "RELATED_TRANSACTIONS": "Related Transactions",
    "RELATED_TRANSACTIONS_AMOUNT": "Related Transactions Amount",
}

_HEADER = '''"""Notion property IDs for the Transactions data source.

AUTO-GENERATED by scripts/gen_property_ids.py — do not hand-edit the IDs.

Notion property IDs are stable across renames, so the sync keys writes/reads by
ID (not display name). Renaming a property in the Notion UI therefore never
breaks anything. Regenerate only if the data source is recreated.

``NAMES`` keeps the display name each ID mapped to at generation time, for
migrations.py (which must create properties BY name) and for readability.
"""

from __future__ import annotations


class P:
    """Stable Notion property IDs (reference these, never the display names)."""

'''


async def main() -> None:
    key = get_notion_api_key()
    url = f"https://api.notion.com/v1/data_sources/{NOTION_TRANSACTIONS_DATA_SOURCE_ID}"
    headers = {"Authorization": f"Bearer {key}", "Notion-Version": NOTION_API_VERSION}
    async with httpx.AsyncClient(timeout=30) as c:
        props = (await c.get(url, headers=headers)).json()["properties"]

    name_to_id = {name: p["id"] for name, p in props.items()}
    missing = [n for n in SEMANTIC_TO_NAME.values() if n not in name_to_id]
    if missing:
        raise SystemExit(f"These names are not in the live schema: {missing}")

    lines = [_HEADER]
    for const, name in SEMANTIC_TO_NAME.items():
        lines.append(f'    {const} = "{name_to_id[name]}"\n')
    lines.append("\n\n")
    lines.append("# Display name each ID mapped to at generation time (for migrations.py).\n")
    lines.append("NAMES: dict[str, str] = {\n")
    for const, name in SEMANTIC_TO_NAME.items():
        lines.append(f'    P.{const}: {name!r},\n')
    lines.append("}\n")

    out = "src/notion_finance_sync/notion/properties.py"
    with open(out, "w") as f:
        f.write("".join(lines))
    print(f"wrote {out} with {len(SEMANTIC_TO_NAME)} pinned property IDs")


if __name__ == "__main__":
    asyncio.run(main())
